#!/bin/sh

set -e
pblue="\033[0;34m"
pgreen="\033[0;32m"
pgray="\033[0;40m"
preset="\033[0m"

PWD=`pwd`

LEIN_BUILD="lein midje"
LEIN_PACKAGE="lein uberjar"
LEIN_INSTALL="lein install"

if [ ! -d "target" ]; then
   mkdir target
fi

echo "${pblue}Building the core${preset}"

cd kuona-core
${LEIN_BUILD}
${LEIN_INSTALL}
cd ..

echo "${pblue}Building the API${preset}"

cd kuona
${LEIN_BUILD}
${LEIN_PACKAGE}
cd ..


find collectors -iname 'project.clj' -exec echo "»»» Building: " {} \; -execdir ${LEIN_BUILD} \; -exec echo "»»» Installing (local): " {} \; -execdir ${LEIN_PACKAGE} \;

find . -iname '*standalone.jar' -not -path './target' -exec cp -f {} ./target \;

echo "${pblue}Binaries collected to ./target${preset}"
