#!/bin/sh
set -e
set -o errexit
set -o nounset

readonly pblue="\033[0;34m"
readonly pgreen="\033[0;32m"
readonly pgray="\033[0;40m"
readonly preset="\033[0m"

function banner() {
    local text=$1

    echo "${pblue}"
    figlet -f cybermedium "${text}"
    echo "${preset}"
}

PWD=`pwd`

readonly LEIN_BUILD="lein midje"
readonly LEIN_PACKAGE="lein uberjar"
readonly LEIN_INSTALL="lein install"
readonly MAVEN_BUILD="mvn clean install"

# Having a namespace call snapshot is possibly the cause of this error
export LEIN_SNAPSHOTS_IN_RELEASE=

if [ ! -d "target" ]; then
   mkdir target
fi


banner "Building collector libs"

find collectors/maven -iname 'pom.xml' -not -path '*/test/*' -execdir ${MAVEN_BUILD} \;
find collectors/lib -iname 'pom.xml' -not -path '*/test/*' -execdir ${MAVEN_BUILD} \;

banner "Building core"

cd kuona-core
${LEIN_BUILD}
${LEIN_INSTALL}
cd ..

banner "Building the API"

cd kuona-api
${LEIN_BUILD}
${LEIN_PACKAGE}
cd ..

banner "Building the dashboard"
cd dashboard/
grunt build
cd ..

banner "Building Collectors"

find collectors -iname 'project.clj' -exec echo "»»» Building: " {} \; -execdir ${LEIN_BUILD} \; -exec echo "»»» Installing (local): " {} \; -execdir ${LEIN_PACKAGE} \;

find . -iname 'gruntfile.js' -not -path '*/node_modules/*' -exec echo "»»» Building: " {} \; -execdir grunt build \;

find . -iname '*standalone.jar' -not -path './target' -exec cp -f {} ./target \;

echo "${pblue}Binaries collected to ./target${preset}"
