#!/bin/sh

set -e
pblue="\033[0;34m"
pgreen="\033[0;32m"
preset="\033[0m"

PWD=`pwd`

echo "${pblue}Kuona developer setup${preset} for ${pgreen}${PWD}${preset}"

echo "${pblue}Installing required tools using hombrew and bundle${preset}"
brew bundle
echo "${pblue}Setting up web development environment${preset}"
cd dashboard; sh dev-setup; cd ..

echo "${pblue}Creating logging directory${preset}"
sudo mkdir -p /var/log/kuona
sudo chown $(whoami) /var/log/kuona


find . -iname 'project.clj' -exec echo "Resolving dependencies for " {} \; -execdir lein deps \;

if [ ! -d "kuona-collector-lib/test-repo" ]; then
   git clone git@github.com:grahambrooks/functional-event-store.git kuona-collector-lib/test-repo
fi

echo "${pgreen}Ready to develop! Start with the readme.${preset}"
