#!/bin/zsh

set -e
set -o errexit
set -o nounset

readonly pblue="\033[0;34m"
readonly pgreen="\033[0;32m"
readonly pgray="\033[0;40m"
readonly preset="\033[0m"

function banner() {
  local text=$1

  echo "${pblue}"
  figlet -f cybermedium "${text}"
  echo "${preset}"
}

PWD=`pwd`

banner "Kuona dev setup"

echo
echo "${pblue}Kuona developer setup${preset} for ${pgreen}${PWD}${preset}"

if command -v brew >/dev/null 2>&1; then
  echo "${pblue}Installing required tools using hombrew and bundle${preset}"
  brew bundle
fi


if ! command -v grunt >/dev/null 2>&1; then
    echo "${pblue}Installing required tools using hombrew and bundle${preset}"
    npm install -g grunt-cli
fi

echo "${pblue}Setting up web development environment${preset}"
cd dashboard; npm install; cd ..

if ! [ -d "test/test-repo" ]; then
  git clone https://github.com/grahambrooks/functional-event-store.git test/test-repo
fi

if ! [ -d "test/dependency-test-repo" ]; then
  git clone https://github.com/grahambrooks/java-nio-socket-server.git test/dependency-test-repo
fi

function symlink_core {
  local p=$1
  
  if ! [ -d "${p}/checkouts" ]; then
    mkdir "${p}/checkouts"
  fi
  
  if ! [ -h "${p}/checkouts/kuona-core" ]; then
    ln -s "${PWD}/kuona-core" "${p}/checkouts/kuona-core"
  fi
}

symlink_core "kuona-api"
symlink_core "tools/github-crawler"
symlink_core "tools/tfs-crawler"

ln -s "${PWD}/dashboard/out" "kuona-api/resources/public"

echo "${pgreen}Ready to develop! Start with the readme.${preset}"
