#!/bin/sh

set -e
set -o errexit
set -o nounset

readonly pblue="\033[0;34m"
readonly pgreen="\033[0;32m"
readonly preset="\033[0m"

function banner() {
    local text=$1

    echo "${pblue}"
    figlet -f cybermedium "${text}"
    echo "${preset}"
}

PWD=`pwd`

if [ -z "$BUILD_NUMBER" ]
   then
         echo "SNAPSHOT BUILD"
   else
    build=$BUILD_NUMBER
    echo "Versioned build ${build}"
    find . -iname 'project.clj' -exec sed -i '' -e "s/-SNAPSHOT/\.${build}/g" {} \;
  fi

