---
- hosts: kuona
  remote_user: deploy
  become: true
  become_user: root
  vars:
    kuona_home: /home/kuona
    collectors_home: "{{kuona_home}}/collectors"
    working_directory: "{{kuona_home}}/working"
    git_collector_version: "0.2.2"
    dashboard_version: 0.2.2-SNAPSHOT
  tasks:
  - name: Test connection
    ping:
      
  - name: "Deploy environment service"
    copy: src="../target/environment-service-0.0.1-standalone.jar" dest="{{kuona_home}}" owner=kuona group=kuona
  - name: Creating convenience symlink
    file: src="{{kuona_home}}/environment-service-0.0.1-standalone.jar" dest="{{kuona_home}}/environment-service.jar" state=link

  - name: Creating service control script for service
    template: src=init.d.j2 dest="/etc/init.d/kuona-environment-service" mode=u+x
    vars:
      jar: "{{kuona_home}}/environment-service.jar"
      pidfile: "{{kuona_home}}/environment-service.pid"
    
  - name: "Restart Kuona environment service"
    service: name=kuona-environment-service state=restarted
    
