GET http://localhost:9001/

# Get a list of configured environments
GET http://localhost:9001/api/environments

#
POST http://localhost:9001/api/environments
Content-Type: application/json

{
	"environment": {
	"tags": [
	        "dev",
        	"blue-green"
      	],
	"comment":
	  	{ "assessment": "Available",
 		   "message": "@graham Everything is pretty good"
	     	},
      	
      	"status": "up",
	"name": "DEVX200"
    	}
}

# Get environment
GET http://localhost:9001/api/environments/DEVX200

# Update the comment
POST http://localhost:9001/api/environments/DEVX200/comments
Content-Type: application/json

{ "comment":
  { "assessment": "Available",
    "message": "@graham Everything is pretty good so far"
  }
}



#
POST http://kuona.io:9001/api/environments
Content-Type: application/json

{
	"environment": {
	"tags": [
	        "dev",
        	"blue-green"
      	],
	"comment":
	  	{ "assessment": "Available",
 		   "message": "@graham Everything is pretty good"
	     	},
      	
      	"status": "up",
	"name": "DEVX200"
    	}
}
